<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.jkiss.dbeaver</groupId>
        <artifactId>plugins</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../</relativePath>
    </parent>
    <artifactId>org.jkiss.dbeaver.ext.turbographpp.javafx</artifactId>
    <version>1.0.0</version>
    <packaging>eclipse-plugin</packaging>

    <properties>
        <javafx-version>23.0.2</javafx-version>
    </properties>

    <build>
        <plugins>
            <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <executions>
                <execution>
                    <id>copy</id>
                    <phase>process-resources</phase> 
                    <goals>
                        <goal>copy</goal>
                    </goals>
                    <configuration>
                        <artifactItems>
                            <!-- For Windows -->
    						<artifactItem>
    							<groupId>org.openjfx</groupId>
    							<artifactId>javafx-base</artifactId>
    							<version>${javafx-version}</version>
    							<type>jar</type>
                                <classifier>win</classifier>
       							<outputDirectory>${project.build.directory}/classes/win</outputDirectory>
    							<destFileName>javafx.base.jar</destFileName>
    						</artifactItem>
                            <artifactItem>
    							<groupId>org.openjfx</groupId>
    							<artifactId>javafx-controls</artifactId>
    							<version>${javafx-version}</version>
    							<type>jar</type>
                                <classifier>win</classifier>
                                <outputDirectory>${project.build.directory}/classes/win</outputDirectory>
    							<destFileName>javafx.controls.jar</destFileName>
    						</artifactItem>
                            <artifactItem>
    							<groupId>org.openjfx</groupId>
    							<artifactId>javafx-graphics</artifactId>
    							<version>${javafx-version}</version>
    							<type>jar</type>
                                <classifier>win</classifier>
                                <outputDirectory>${project.build.directory}/classes/win</outputDirectory>
    							<destFileName>javafx.graphics.jar</destFileName>
    						</artifactItem>
                            <!-- For Linux -->
                            <artifactItem>
    							<groupId>org.openjfx</groupId>
    							<artifactId>javafx-base</artifactId>
    							<version>${javafx-version}</version>
    							<type>jar</type>
                                <classifier>linux</classifier>
       							<outputDirectory>${project.build.directory}/classes/linux</outputDirectory>
    							<destFileName>javafx.base.jar</destFileName>
    						</artifactItem>
                            <artifactItem>
    							<groupId>org.openjfx</groupId>
    							<artifactId>javafx-controls</artifactId>
    							<version>${javafx-version}</version>
    							<type>jar</type>
                                <classifier>linux</classifier>
                                <outputDirectory>${project.build.directory}/classes/linux</outputDirectory>
    							<destFileName>javafx.controls.jar</destFileName>
    						</artifactItem>
                            <artifactItem>
    							<groupId>org.openjfx</groupId>
    							<artifactId>javafx-graphics</artifactId>
    							<version>${javafx-version}</version>
    							<type>jar</type>
                                <classifier>linux</classifier>
                                <outputDirectory>${project.build.directory}/classes/linux</outputDirectory>
    							<destFileName>javafx.graphics.jar</destFileName>
    						</artifactItem>
                            <!-- For Mac -->
                            <artifactItem>
    							<groupId>org.openjfx</groupId>
    							<artifactId>javafx-base</artifactId>
    							<version>${javafx-version}</version>
    							<type>jar</type>
                                <classifier>mac</classifier>
       							<outputDirectory>${project.build.directory}/classes/mac</outputDirectory>
    							<destFileName>javafx.base.jar</destFileName>
    						</artifactItem>
                            <artifactItem>
    							<groupId>org.openjfx</groupId>
    							<artifactId>javafx-controls</artifactId>
    							<version>${javafx-version}</version>
    							<type>jar</type>
                                <classifier>mac</classifier>
                                <outputDirectory>${project.build.directory}/classes/mac</outputDirectory>
    							<destFileName>javafx.controls.jar</destFileName>
    						</artifactItem>
                            <artifactItem>
    							<groupId>org.openjfx</groupId>
    							<artifactId>javafx-graphics</artifactId>
    							<version>${javafx-version}</version>
    							<type>jar</type>
                                <classifier>mac</classifier>
                                <outputDirectory>${project.build.directory}/classes/mac</outputDirectory>
    							<destFileName>javafx.graphics.jar</destFileName>
    						</artifactItem>
    					</artifactItems>
                    </configuration>
                </execution>
            </executions>
            </plugin>
        </plugins>
    </build>
</project>
